apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-data
  namespace: default
  labels:
    app: test
spec:
  storageClassName: lab-disk-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi