apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-data
  namespace: default
  labels:
    app: test
  annotations:
    ragdollphysics.org/disk-node: "docker-desktop"
    ragdollphysics.org/shared-storage-path: "testpath"
spec:
  storageClassName: lab-disk-shared
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi